package main

import (
	"crypto/ecdh"
	"crypto/rand"
	"encoding/base64"
	"encoding/hex"
	"flag"
	"fmt"
	"os"
	"time"
)

// keygenMain implements the `vinereal-server keygen` subcommand: it generates
// a REALITY X25519 key pair and a batch of short IDs for a deployment, then
// prints the values to paste into the server YAML and the client SDK.
//
// Run as:
//
//	vinereal-server keygen
//	vinereal-server keygen -format go -shortids 5
func keygenMain(args []string) int {
	fs := flag.NewFlagSet("keygen", flag.ExitOnError)
	shortIDCount := fs.Int("shortids", 3, "number of additional random short IDs to generate (the all-zero default short id is always included)")
	shortIDBytes := fs.Int("shortid-bytes", 8, "length in bytes of each generated short id (1-8)")
	format := fs.String("format", "text", "output format: text | go")
	fs.Parse(args)

	if *shortIDBytes < 1 || *shortIDBytes > 8 {
		fmt.Fprintln(os.Stderr, "keygen: -shortid-bytes must be between 1 and 8")
		return 2
	}

	privKey, err := ecdh.X25519().GenerateKey(rand.Reader)
	if err != nil {
		fmt.Fprintf(os.Stderr, "keygen: generate key: %v\n", err)
		return 1
	}
	privB64 := base64.RawURLEncoding.EncodeToString(privKey.Bytes())
	pubB64 := base64.RawURLEncoding.EncodeToString(privKey.PublicKey().Bytes())

	shortIDs := []string{""} // the all-zero default short id is always valid
	for i := 0; i < *shortIDCount; i++ {
		buf := make([]byte, *shortIDBytes)
		if _, err := rand.Read(buf); err != nil {
			fmt.Fprintf(os.Stderr, "keygen: generate short id: %v\n", err)
			return 1
		}
		shortIDs = append(shortIDs, hex.EncodeToString(buf))
	}

	switch *format {
	case "text":
		printText(privB64, pubB64, shortIDs)
	case "go":
		printText(privB64, pubB64, shortIDs)
		fmt.Println()
		printGo(pubB64, shortIDs)
	default:
		fmt.Fprintf(os.Stderr, "keygen: unknown -format %q (want text|go)\n", *format)
		return 2
	}
	return 0
}

func printText(privB64, pubB64 string, shortIDs []string) {
	fmt.Printf("# REALITY key material, generated %s\n", time.Now().UTC().Format(time.RFC3339))
	fmt.Println("# All of this is meant to be static per-deployment: bake it into the server")
	fmt.Println("# YAML and the client SDK once, and reuse it across any number of")
	fmt.Println("# interchangeable reverse-proxy nodes.")
	fmt.Println()
	fmt.Println("# --- server config.yaml (reality:) --- keep private_key_b64 secret, server-only")
	fmt.Printf("private_key_b64: %q\n", privB64)
	fmt.Println("short_ids:")
	for _, id := range shortIDs {
		fmt.Printf("  - %q\n", id)
	}
	fmt.Println()
	fmt.Println("# --- client SDK values --- safe to embed in a compiled app binary")
	fmt.Printf("public_key_b64: %q\n", pubB64)
	fmt.Println("# pick ONE short id per client identity/build to embed as ShortIDHex:")
	for _, id := range shortIDs {
		fmt.Printf("  - %q\n", id)
	}
}

func printGo(pubB64 string, shortIDs []string) {
	chosen := shortIDs[len(shortIDs)-1] // last generated (non-default) short id as a sane example
	fmt.Println("// --- paste as client/vinereal/config_prod.go ---")
	fmt.Println("// Code generated by `vinereal-server keygen -format go`. Review before committing:")
	fmt.Println("// PublicKeyB64 and ShortIDHex are safe to ship in a public app binary, but")
	fmt.Println("// double-check ServerAddr and ServerName are filled in for your deployment.")
	fmt.Println("package vinereal")
	fmt.Println()
	fmt.Println(`import "github.com/VineLink-Lab/VineReal/shared/visionframe"`)
	fmt.Println()
	fmt.Println("var ProdConfig = Config{")
	fmt.Println(`	ServerAddr:         "CHANGE_ME_HOST:443",`)
	fmt.Println(`	ServerName:         "CHANGE_ME_DECOY_SNI",`)
	fmt.Printf("\tPublicKeyB64:       %q,\n", pubB64)
	fmt.Printf("\tShortIDHex:         %q,\n", chosen)
	fmt.Println(`	Fingerprint:        "chrome_auto",`)
	fmt.Println("\tHandshakeTimeoutMS: 10_000,")
	fmt.Println("\tVision:             visionframe.DefaultConfig,")
	fmt.Println("}")
}
