// Command realitykeygen generates a REALITY X25519 key pair and a batch of
// short IDs for a vinereal deployment. It is intentionally dependency-free
// (stdlib only: crypto/ecdh, crypto/rand) so that building this one command
// never pulls in xtls/reality or any of its transitive dependencies, even
// though it lives inside the server module.
package main

import (
	"crypto/ecdh"
	"crypto/rand"
	"encoding/base64"
	"encoding/hex"
	"flag"
	"fmt"
	"os"
	"time"
)

// version is stamped at build time via
// -ldflags "-X main.version=$(git describe --tags)" and defaults to "dev" for
// local, untagged builds.
var version = "dev"

func main() {
	showVersion := flag.Bool("version", false, "print version and exit")
	shortIDCount := flag.Int("shortids", 3, "number of additional random short IDs to generate (the all-zero default short id is always included)")
	shortIDBytes := flag.Int("shortid-bytes", 8, "length in bytes of each generated short id (1-8)")
	format := flag.String("format", "text", "output format: text | go")
	flag.Parse()

	if *showVersion {
		fmt.Println(version)
		return
	}

	if *shortIDBytes < 1 || *shortIDBytes > 8 {
		fmt.Fprintln(os.Stderr, "realitykeygen: -shortid-bytes must be between 1 and 8")
		os.Exit(1)
	}

	privKey, err := ecdh.X25519().GenerateKey(rand.Reader)
	if err != nil {
		fmt.Fprintf(os.Stderr, "realitykeygen: generate key: %v\n", err)
		os.Exit(1)
	}
	privB64 := base64.RawURLEncoding.EncodeToString(privKey.Bytes())
	pubB64 := base64.RawURLEncoding.EncodeToString(privKey.PublicKey().Bytes())

	shortIDs := []string{""} // the all-zero default short id is always valid
	for i := 0; i < *shortIDCount; i++ {
		buf := make([]byte, *shortIDBytes)
		if _, err := rand.Read(buf); err != nil {
			fmt.Fprintf(os.Stderr, "realitykeygen: generate short id: %v\n", err)
			os.Exit(1)
		}
		shortIDs = append(shortIDs, hex.EncodeToString(buf))
	}

	switch *format {
	case "text":
		printText(privB64, pubB64, shortIDs)
	case "go":
		printText(privB64, pubB64, shortIDs)
		fmt.Println()
		printGo(pubB64, shortIDs)
	default:
		fmt.Fprintf(os.Stderr, "realitykeygen: unknown -format %q (want text|go)\n", *format)
		os.Exit(1)
	}
}

func printText(privB64, pubB64 string, shortIDs []string) {
	fmt.Printf("# REALITY key material, generated %s\n", time.Now().UTC().Format(time.RFC3339))
	fmt.Println("# All of this is meant to be static per-deployment: bake it into the server")
	fmt.Println("# YAML and the client SDK once, and reuse it across any number of")
	fmt.Println("# interchangeable reverse-proxy nodes.")
	fmt.Println()
	fmt.Println("# --- server config.yaml (reality:) --- keep private_key_b64 secret, server-only")
	fmt.Printf("private_key_b64: %q\n", privB64)
	fmt.Println("short_ids:")
	for _, id := range shortIDs {
		fmt.Printf("  - %q\n", id)
	}
	fmt.Println()
	fmt.Println("# --- client SDK values --- safe to embed in a compiled app binary")
	fmt.Printf("public_key_b64: %q\n", pubB64)
	fmt.Println("# pick ONE short id per client identity/build to embed as ShortIDHex:")
	for _, id := range shortIDs {
		fmt.Printf("  - %q\n", id)
	}
}

func printGo(pubB64 string, shortIDs []string) {
	chosen := shortIDs[len(shortIDs)-1] // last generated (non-default) short id as a sane example
	fmt.Println("// --- paste as client/vinereal/config_prod.go ---")
	fmt.Println("// Code generated by realitykeygen. Review before committing: PublicKeyB64 and")
	fmt.Println("// ShortIDHex are safe to ship in a public app binary, but double-check ServerAddr")
	fmt.Println("// and ServerName are filled in for your actual deployment before use.")
	fmt.Println("package vinereal")
	fmt.Println()
	fmt.Println(`import "github.com/VineLink-Lab/VineReal/shared/visionframe"`)
	fmt.Println()
	fmt.Println("var ProdConfig = Config{")
	fmt.Println(`	ServerAddr:         "CHANGE_ME_HOST:443",`)
	fmt.Println(`	ServerName:         "CHANGE_ME_DECOY_SNI",`)
	fmt.Printf("\tPublicKeyB64:       %q,\n", pubB64)
	fmt.Printf("\tShortIDHex:         %q,\n", chosen)
	fmt.Println(`	Fingerprint:        "chrome_auto",`)
	fmt.Println("\tHandshakeTimeoutMS: 10_000,")
	fmt.Println("\tVision:             visionframe.DefaultConfig,")
	fmt.Println("}")
}
